services:
  app:
    image: nginx
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: nginx
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
          test: ["CMD", "echo", "ok"]
          interval: 30s
          timeout: 10s
          retries: 3
